build:

	docker-compose build 

run:

	docker-compose up -d

down:

	- docker-compose down

redis_console : 

	docker exec -it redis_service redis-cli

sql_console:

	docker exec -it mysql_service bash 

mongo_console:

	docker exec -it mongo_service bash