# Generated by Django 4.1 on 2022-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('registration', models.DateField(auto_now=True, verbose_name='registration')),
                ('active', models.CharField(max_length=3, verbose_name='active')),
            ],
        ),
    ]
