# Generated by Django 4.1.1 on 2022-09-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('rol', models.CharField(choices=[('0', 'MANAGER'), ('1', 'EMPLEADO'), ('2', 'CONTABLE')], max_length=1, verbose_name='roles')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online_store.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=20, verbose_name='nombre')),
                ('tipo_tienda', models.CharField(choices=[('0', 'consumo'), ('1', 'electronica'), ('2', 'moda'), ('3', 'deporte')], max_length=1, verbose_name='tipo_tienda')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.empleado')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online_store.manager')),
            ],
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['rol'], name='idx_empleado_rol'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['nombre', 'rol'], name='idx_empleado_nombre_rol'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['nombre'], name='idx_empleado_nombre'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['id', 'nombre_tienda'], name='idx_tienda_id_nombre_tienda'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['empleado'], name='idx_tienda_empleado'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['manager'], name='idx_tienda__manager'),
        ),
        migrations.AddIndex(
            model_name='tienda',
            index=models.Index(fields=['id', 'nombre_tienda', 'tipo_tienda', 'empleado', 'manager'], name='idx_tienda_id_s_e_m'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['nombre'], name='idx_manager_nombre'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['id', 'nombre'], name='idx_manager_id_nombre'),
        ),
    ]
