# Generated by Django 4.1.1 on 2022-09-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
    ]
